### ISSUE TITLE
GitHub Pages on a custom domain

### ISSUE THREAD

**Issue by ryanlovett** [Yu-Group/yugroup-website#1]
Do you want to host this site at yugroup.stat.berkeley.edu?

If so, once you [use GitHub Pages](https://help.github.com/en/github/working-with-github-pages/about-github-pages), you can follow the first three steps of [these instructions](https://help.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain) and I'll do the rest.

**Comment by csinva** [comment]
We actually already are hosting this at yugroup.stat.berkeley.edu (we have cloned this repo into the appropriate directory in the yugroup account). This setup works fine for us, so no need to set it up via Github Pages. Thanks!

**Comment by ryanlovett** [comment]
I'm pretty sure it is being hosted at www.stat.berkeley.edu. :)

**Comment by csinva** [comment]
Oh yes you are right! I think that is fine for us for now...will check with Bin to see if she would rather use yugroup.stat.berkeley.edu

**Comment by ryanlovett** [comment]
No problem. The reason I suggest it is that the website wouldn't depend on SCF infrastructure and would probably have better uptime. (I've moved another faculty's site to Google Sites for example.) Another is that you could use GitHub Actions to run parsePub.py.

Just a friendly suggestion -- we'll continue to support the static websites at the SCF.
